language: csharp
sudo: required
dist: trusty
mono: none
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
  - dotnet build StravaClub.sln
  - dotnet test test/StravaClub.Core.Test.csproj
