language: csharp
dotnet: 2.0.0
mono: none
env:
  global:
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  - DOTNET_CLI_TELEMETRY_OPTOUT: 1
script:
- dotnet build
- dotnet test ./test/StravaClub.Core.Test/
deploy:
  provider: gae
  project: strava-club-192713
before_install:
- openssl aes-256-cbc -K $encrypted_1722b0de7371_key -iv $encrypted_1722b0de7371_iv
  -in client-secret.json.enc -out client-secret.json -d
